name: SSE CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: pip install black pytest coverage numpy matplotlib

  style_check:
    name: Format Code
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Black
        run: pip install black

      - name: Auto-Format Code
        run: |
          black .
          git diff --exit-code || (echo "Code was reformatted. Please commit changes." && exit 1)

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install pytest coverage numpy matplotlib

      - name: Run Tests
        run: coverage run -m pytest

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: .coverage
          retention-days: 1
          include-hidden-files: true

  coverage_report:
    name: Generate Coverage Report
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Coverage Tool
        run: pip install coverage

      - name: Download Coverage Data
        uses: actions/download-artifact@v4
        with:
          name: code-coverage

      - name: Generate Report
        run: |
          coverage report -m
          coverage xml

      - name: Upload Coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          retention-days: 14
